---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-values
  namespace: default
data:
    values.yaml: |      
      auth:
        password: "password"
      persistence:
        size: 4Gi
      service:
        type: ClusterIP
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neo4j
  namespace: default
spec:
  interval: 10m0s
  timeout: 5m0s
  chart:
    spec:
      chart: neo4j
      version: '0.3.0'
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
      interval: 10m0s
  releaseName: neo4j
  valuesFrom:
  - kind: ConfigMap
    name: neo4j-values
    valuesKey: values.yaml