apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base
configMapGenerator:
  - name: env-config
    behavior: merge
    literals:
      - operation=""
      # - operation="add"
      # - operation="mul"