apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:7.8.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: SCHEMA_REGISTRY_HOST_NAME
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
        - name: SCHEMA_REGISTRY_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: SCHEMA_REGISTRY_LISTENERS
