apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  type: ClusterIP
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP 
  # from its pool if not specified. You can also specify one manually.
  # loadBalancerIP: 192.168.3.10
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    # - name: https
    #   protocol: TCP
    #   port: 443
    #   targetPort: 443