---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-values
  namespace: default
data:
    values.yaml: |
      controller:
        replicaCount: 3
      persistence:
        size: 10Gi
      listeners:
        client:
          protocol: PLAINTEXT
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: default
spec:
  interval: 10m0s
  timeout: 5m0s
  chart:
    spec:
      chart: kafka
      version: '31.2.0'
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
      interval: 10m0s
  releaseName: kafka
  valuesFrom:
  - kind: ConfigMap
    name: kafka-values
    valuesKey: values.yaml