---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-values
  namespace: default
data:
    values.yaml: |
      architecture: standalone
      persistence:
        size: 4Gi
      auth:
        password: "password"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: default
spec:
  interval: 10m0s
  timeout: 5m0s
  chart:
    spec:
      chart: redis
      version: '20.7.1'
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
      interval: 10m0s
  releaseName: redis
  valuesFrom:
  - kind: ConfigMap
    name: redis-values
    valuesKey: values.yaml