---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: default
spec:
  interval: 10m0s
  timeout: 5m0s
  chart:
    spec:
      chart: redis
      version: '20.7.1'
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
      interval: 10m0s
  releaseName: redis
  # # valuesFiles:
  # #   - values.yaml
  # valuesFrom:
  #   - kind: ConfigMap
  #     name: dev-values
  #     valuesKey: values.yaml