---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-values
  namespace: default
data:
  CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
  CONNECT_REST_PORT: "8083"
  CONNECT_GROUP_ID: connect-group
  CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
  CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
  CONNECT_STATUS_STORAGE_TOPIC: _connect-status
  CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
  CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: connect-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect
  template:
    metadata:
      labels:
        app: connect
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      volumes:
        - name: connect-pv-storage
          persistentVolumeClaim:
            claimName: connect-pvc
      containers:
        - name: connect
          image: confluentinc/cp-server-connect-base:7.8.0
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: "/data/"
              name: connect-pv-storage
          envFrom:
            - configMapRef:
                name: connect-values
          env:
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
