---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnamicharts
  namespace: default
spec:
  type: oci
  interval: 10m0s
  url: oci://registry-1.docker.io/bitnamicharts
