---
apiVersion: v1
kind: ConfigMap
metadata:
  name: control-center-values
  namespace: default
data:
  CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:9092"
  CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: "http://connect:8083"
  CONTROL_CENTER_CONNECT_HEALTHCHECK_ENDPOINT: "/connectors"
  CONTROL_CENTER_REPLICATION_FACTOR: "1"
  CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: "1"
  CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: "1"
  PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
      - name: control-center
        image: confluentinc/cp-enterprise-control-center:7.8.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        envFrom:
          - configMapRef:
              name: control-center-values