---
apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-values
  namespace: default
data:
    values.yaml: |
      replicaCount: 3
      kafka:
        enabled: false
      externalKafka:
        brokers:
          - PLAINTEXT://kafka:9092
        listener:
          protocol: PLAINTEXT
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: schema-registry
  namespace: default
spec:
  interval: 10m0s
  timeout: 5m0s
  chart:
    spec:
      chart: schema-registry
      version: '23.1.3'
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
      interval: 10m0s
  releaseName: schema-registry
  valuesFrom:
  - kind: ConfigMap
    name: schema-registry-values
    valuesKey: values.yaml