---
apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-values
  namespace: default
data:
    values.yaml: |
      replicaCount: 1
      kafka:
        enabled: false
      externalKafka:
        brokers:
          - PLAINTEXT://kafka:9092
        listener:
          protocol: PLAINTEXT