name: Build and push - Demo App to Docker Hub

on:
  push:
    paths: 
      - "demo/**"
      - ".github/workflows/*"

env:
  USERNAME: anderslaunerbaek
  IMAGE_NAME: sdu-se-demo-app

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:demo"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest
          